services:
  bot-gepetesque:
    build: .
    restart: always
    env_file: .env
    volumes:
      - ./bot.db:/app/bot.db
    networks:
      - bot-network

networks:
  bot-network:
    external: true
