services:
  bot:
    build: .
    container_name: my-mc-bot
    env_file: .env
    restart: unless-stopped
    volumes:
      - .:/app
      - ../keys/mc-host.pem:/keys/mc-host.pem:ro
    working_dir: /app
    # -u pour des logs non bufferisés
    command: python -u main.py
